#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias tmsu="sudo sysctl debug.lowpri_throttle_enabled=0"
alias tmsd="sudo sysctl debug.lowpri_throttle_enabled=1"

SPACESHIP_EXIT_CODE_SHOW=true

source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/.iterm2_shell_integration.zsh"

alias uberspike="ssh garkbit@auriga.uberspace.de."
alias ubermetric="ssh owntrout@bellatrix.uberspace.de."
